language: php
sudo: false

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

install: composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
